version: "3"
services:
  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    volumes:
      - ./shared-files:/shared-files
    restart: always
    ports:
      - 3000:3000
    env_file:
      - local.env
    depends_on:
      - mysql

  traningrunner:
    build:
      context: ./training/tools
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./shared-files:/shared-files
    env_file:
      - local.env
    restart: always

  mysql:
    image: mysql:5.7
    volumes:
      - ./mysql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - mysql:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always
    env_file:
      - local.env

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysql

volumes:
  mysql:

networks:
  default:
    external:
      name: ease-training
