version: "3"
services:
  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    ports:
      - 3000:3000
    env_file:
      - .env

  mysql:
    image: mysql
    volumes:
      - ./mysql/schema.sql:/docker-entrypoint-initdb.d
    restart: always
    env_file:
      - .env

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
