version: "3"
services:
  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./shared-files:/shared-files
    restart: always
    ports:
      - 3000:3000
    env_file:
      - local.env
    depends_on:
      - mysql

  traningrunner:
    build:
      context: ./training/tools
      dockerfile: Dockerfile

  mysql:
    image: mysql
    volumes:
      - ./mysql/schema.sql:/docker-entrypoint-initdb.d
      - mysql:/var/lib/mysql
    restart: always
    env_file:
      - local.env

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysql
volumes:
  mysql:
