version: "3"
services:
  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
      
  db:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - .env

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080