classesNames = ['jyz',
                'sflxccz',
                'fxjgb',
                'fzc',
                'xcxj',
                'xdzc',
                'szxjgb',
                'fhjyz',
                'jyh',
                'sflzc',
                'sflnzcz',
                'dpjjyh',
                'bsp',
                'bxgqnq',
                'djlsbhm',
                'sjlb',
                'gjxqnc',
                'sxtzb']
