FROM postor/ease-training

COPY ./tools/package*.json ./tools/

RUN set -x \
  && cd tools \
  && npm install

COPY . .


ENTRYPOINT ["/training/train.sh"]
CMD ["-c","print('check https://github.com/postor/ease-training for usage')"]
